#!/usr/bin/env python3
"""
Creatio 8.3 Source Code Indexer
================================
Indexes and extracts patterns from the local Creatio 8.3 installation.
Creates a searchable reference of entity schemas, services, event handlers,
business rules, and integration patterns.

Source: /mnt/c/Creatio/8.3.0.3031_SalesEnterprise_Marketing_ServiceEnterprise_Softkey_MSSQL_ENU/

Key directories:
- Terrasoft.WebApp/Terrasoft.Configuration/Pkg/  — 170 packages with C# source
- Terrasoft.WebApp/ClientApp/  — 25K compiled JS files (mostly bundled)
- bin/  — 225+ compiled DLLs

Focus: Authored C# code in Pkg/*/Files/ (not Autogenerated/)

Usage:
    python3 source_code_indexer.py                    # Full index
    python3 source_code_indexer.py --top=20            # Top 20 packages by code volume
    python3 source_code_indexer.py --package CrtCore    # Index specific package
    python3 source_code_indexer.py --patterns           # Extract common patterns only
    python3 source_code_indexer.py --status             # Show index status
"""

import os
import sys
import json
import re
import argparse
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Set, Optional, Tuple
from dataclasses import dataclass, field, asdict
from collections import defaultdict

# ─── Configuration ────────────────────────────────────────────────────────────

# Override with CREATIO_ROOT env var, e.g. CREATIO_ROOT=/mnt/c/Creatio/D3_sales-enterprise
# (D3 = 8.3.3, 225 packages — closer to current GA than the old 8.3.0 installer extract).
CREATIO_ROOT = Path(os.environ.get(
    "CREATIO_ROOT",
    "/mnt/c/Creatio/8.3.0.3031_SalesEnterprise_Marketing_ServiceEnterprise_Softkey_MSSQL_ENU"))
PKG_DIR = CREATIO_ROOT / "Terrasoft.WebApp" / "Terrasoft.Configuration" / "Pkg"
DEFAULT_OUTPUT = Path("./creatio-source-index")

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%H:%M:%S'
)
log = logging.getLogger("source-indexer")


# ─── Data Structures ─────────────────────────────────────────────────────────

@dataclass
class CSharpFile:
    path: str
    package: str
    filename: str
    namespace: str = ""
    classes: List[Dict] = field(default_factory=list)
    interfaces: List[str] = field(default_factory=list)
    base_classes: List[str] = field(default_factory=list)
    usings: List[str] = field(default_factory=list)
    attributes: List[str] = field(default_factory=list)
    methods: List[Dict] = field(default_factory=list)
    properties: List[Dict] = field(default_factory=list)
    line_count: int = 0
    is_autogenerated: bool = False
    category: str = "unknown"


@dataclass
class PackageIndex:
    name: str
    authored_cs: int = 0
    autogen_cs: int = 0
    js_files: int = 0
    descriptor: Dict = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)
    category: str = "unknown"
    files: List[CSharpFile] = field(default_factory=list)
    patterns: List[str] = field(default_factory=list)
    entities: List[str] = field(default_factory=list)
    services: List[str] = field(default_factory=list)
    event_handlers: List[str] = field(default_factory=list)


# ─── C# Parser ───────────────────────────────────────────────────────────────

class CSharpParser:
    """Lightweight C# source file parser for pattern extraction."""

    # Patterns
    RE_NAMESPACE = re.compile(r'namespace\s+([\w.]+)')
    RE_CLASS = re.compile(r'(?:public|internal|private|protected)?\s*(?:abstract|sealed|static|partial)?\s*class\s+(\w+)(?:\s*:\s*(.+?))?(?:\s*\{|$)', re.MULTILINE)
    RE_INTERFACE = re.compile(r'(?:public|internal)?\s*interface\s+(\w+)')
    RE_METHOD = re.compile(r'(?:public|protected|private|internal|override|virtual|static|async)\s+(?:\w+(?:<[^>]+>)?)\s+(\w+)\s*\(([^)]*)\)')
    RE_PROPERTY = re.compile(r'(?:public|protected|private|internal)\s+(?:virtual|override|static)?\s*(\w+(?:<[^>]+>)?)\s+(\w+)\s*\{')
    RE_USING = re.compile(r'using\s+([\w.]+)\s*;')
    RE_ATTRIBUTE = re.compile(r'\[(\w+)(?:\(.*?\))?\]')

    # Pattern detection
    RE_ENTITY_EVENT = re.compile(r'(?:OnSaving|OnSaved|OnDeleting|OnDeleted|OnInserting|OnInserted|OnUpdating|OnUpdated)')
    RE_PROCESS_ELEMENT = re.compile(r'ProcessFlowElement|ProcessSchemaUserTask|BaseProcessParametersEditModule')
    RE_WEB_SERVICE = re.compile(r'(?:ServiceRoute|HttpHandler|IReadOnlyComposableRequestHandler|RestRoute)')
    RE_ESQL = re.compile(r'EntitySchemaQuery|new\s+Select\(|InsertQuery|UpdateQuery|DeleteQuery')
    RE_BUSINESS_RULE = re.compile(r'BusinessRuleModule|BusinessRule')

    def parse_file(self, path: Path, package_name: str) -> CSharpFile:
        """Parse a C# file and extract structure."""
        try:
            content = path.read_text(encoding='utf-8-sig', errors='replace')
        except Exception:
            return CSharpFile(path=str(path), package=package_name, filename=path.name)

        result = CSharpFile(
            path=str(path),
            package=package_name,
            filename=path.name,
            line_count=content.count('\n') + 1,
            is_autogenerated='Autogenerated' in str(path),
        )

        # Namespace
        ns_match = self.RE_NAMESPACE.search(content)
        result.namespace = ns_match.group(1) if ns_match else ""

        # Usings
        result.usings = self.RE_USING.findall(content)

        # Classes with base classes
        for match in self.RE_CLASS.finditer(content):
            class_name = match.group(1)
            bases = match.group(2)
            base_list = [b.strip() for b in bases.split(',')] if bases else []
            result.classes.append({
                'name': class_name,
                'bases': base_list,
            })
            result.base_classes.extend(base_list)

        # Interfaces
        result.interfaces = self.RE_INTERFACE.findall(content)

        # Methods (only for authored files to avoid noise)
        if not result.is_autogenerated:
            for match in self.RE_METHOD.finditer(content):
                result.methods.append({
                    'name': match.group(1),
                    'params': match.group(2).strip(),
                })

        # Properties (only for authored)
        if not result.is_autogenerated:
            for match in self.RE_PROPERTY.finditer(content):
                result.properties.append({
                    'type': match.group(1),
                    'name': match.group(2),
                })

        # Attributes
        result.attributes = list(set(self.RE_ATTRIBUTE.findall(content)))

        # Categorize
        result.category = self._categorize(content, result)

        return result

    def _categorize(self, content: str, result: CSharpFile) -> str:
        """Categorize the file by its patterns."""
        categories = []

        if self.RE_ENTITY_EVENT.search(content):
            categories.append("entity_event_handler")
        if self.RE_PROCESS_ELEMENT.search(content):
            categories.append("process_element")
        if self.RE_WEB_SERVICE.search(content):
            categories.append("web_service")
        if self.RE_ESQL.search(content):
            categories.append("data_access")
        if self.RE_BUSINESS_RULE.search(content):
            categories.append("business_rule")

        # Check base classes for patterns
        for cls in result.classes:
            for base in cls.get('bases', []):
                if 'EventListener' in base or 'EventSubProcess' in base:
                    categories.append("event_listener")
                elif 'BaseProcessUserTask' in base or 'ProcessUserTask' in base:
                    categories.append("process_user_task")
                elif 'BaseService' in base or 'RestService' in base:
                    categories.append("rest_service")
                elif 'BaseEntity' in base or 'Entity' == base:
                    categories.append("entity")
                elif 'BaseSchema' in base:
                    categories.append("schema")

        return ",".join(categories) if categories else "general"


# ─── Package Categorizer ─────────────────────────────────────────────────────

PACKAGE_CATEGORIES = {
    'core': ['CrtBase', 'CrtCore', 'CrtCoreBase', 'CrtBaseConsts', 'CrtBfUtilities',
             'CrtDataForge', 'CrtFeatureToggling', 'FeatureToggling', 'CrtMacrosBase',
             'CrtMessage', 'CrtWebFarm', 'CrtTranslation', 'CrtUserLevelSchema',
             'CalendarBase', 'CrtCalendar'],
    'ui_framework': ['CrtNUI', 'CrtUIPlatform', 'CrtUIPlatform7x', 'CrtUISwitcher',
                     'CrtUIv2', 'CrtDesignerTools', 'PivotTable', 'RelationshipDesigner',
                     'CoreForecast', 'CrtAnalyticsDashboard'],
    'sales': ['CrtLead', 'CrtOpportunity', 'CrtOpportunityManagement', 'CrtOrder',
              'CrtContract', 'CrtInvoice', 'CrtProductBase', 'CrtProductCatalogue',
              'CrtDocument', 'CrtSupplyPayment', 'CrtPlaybook', 'CrtNextStep',
              'CrtSpecification', 'Opportunity'],
    'marketing': ['CrtEmailDesigner', 'CrtEmailDesignerAI', 'CrtEmailSender',
                  'CrtEmailTemplate', 'CrtBulkEmailCopilot', 'CrtCampaignDesigner7x',
                  'CrtGoogleAnalytics', 'CrtDigitalAdsApp', 'CrtMatomoConnector',
                  'CrtLandingPage', 'CrtContentDesigner', 'CrtHTMLPageDesigner',
                  'CrtWebFormBase', 'CrtWebhookServiceBase', 'CrtMLangContent',
                  'CrtDynamicContent7x', 'CrtTouchPoint', 'CrtTouchPointBase',
                  'CrtJunkFilter', 'ContentBuilder'],
    'service': ['CrtCaseService', 'CrtCaseManagement', 'CrtCase7x', 'CrtSLM',
                'CrtSLMITILService', 'CrtKnowledgeManagementApp', 'CrtPortal',
                'CaseService', 'ServiceDesigner', 'ServiceModel', 'SspWorkplace'],
    'ai_copilot': ['CrtCopilot', 'CrtCopilotStudio', 'CrtStudioCopilot', 'CrtAIEmbedded',
                   'CrtML', 'CrtMLLeadConversion', 'CrtMLLeadScoring',
                   'CrtMLOpportunityScoring', 'MLCaseClassification', 'MLSimilarCaseSearch',
                   'MLProcessDesigner', 'CrtKnowledgeAI', 'CrtCustomer360AI',
                   'CrtProductivityCopilot', 'CrtCaseKnowledgeCopilot',
                   'CrtOrderContractCopilot', 'CrtCaseCopilot', 'CrtEmailDesignerAI',
                   'CrtSimilarLead', 'CrtRecommendedProduct'],
    'customer360': ['CrtCustomer360App', 'CrtCustomer360Mobile', 'CrtC360InUiV2'],
    'integration': ['IntegrationV2', 'CrtSmsIntegration', 'CrtCall', 'Finesse',
                    'OmnichannelMessaging', 'CrtOmnichannelApp',
                    'CrtTechUserCreatioALMIntegration'],
    'security': ['CrtSecurity', 'CrtSecurity7x', 'OAuth20', 'OpenIdAuth',
                 'SsoSettings', 'XSSProtection', 'CSP', 'CrtTechnicalUsers'],
    'mobile': ['CrtProductivityMobile', 'CrtCustomer360Mobile',
               'CrtMobileFreedomUIStylesFor7x'],
}


def categorize_package(name: str) -> str:
    """Determine category for a package name."""
    for category, packages in PACKAGE_CATEGORIES.items():
        if name in packages:
            return category
    # Heuristic matching
    if 'InC360' in name:
        return 'customer360_adapter'
    if 'InLeadOpp' in name or 'InCaseMgmt' in name:
        return 'cross_module_adapter'
    if '7x' in name:
        return 'legacy_compat'
    if 'Copilot' in name:
        return 'ai_copilot'
    if 'App' in name and name.startswith('Crt'):
        return 'app_shell'
    return 'other'


# ─── Main Indexer ─────────────────────────────────────────────────────────────

class SourceCodeIndexer:
    """Indexes Creatio 8.3 source code."""

    def __init__(self, output_dir: Path = DEFAULT_OUTPUT,
                 pkg_dir: Path = PKG_DIR):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.pkg_dir = pkg_dir
        self.parser = CSharpParser()
        self.packages: Dict[str, PackageIndex] = {}

    def index_all(self, top_n: int = None, package_filter: str = None):
        """Index all packages."""
        log.info("=" * 60)
        log.info("Creatio 8.3 Source Code Indexer")
        log.info(f"Source: {self.pkg_dir}")
        log.info("=" * 60)

        if not self.pkg_dir.exists():
            log.error(f"Package directory not found: {self.pkg_dir}")
            return

        # Discover packages
        pkg_dirs = sorted([d for d in self.pkg_dir.iterdir() if d.is_dir()])

        if package_filter:
            pkg_dirs = [d for d in pkg_dirs if package_filter.lower() in d.name.lower()]

        log.info(f"Found {len(pkg_dirs)} packages")

        # First pass: count files per package
        pkg_stats = []
        for pkg_path in pkg_dirs:
            name = pkg_path.name
            authored_cs = list((pkg_path / "Files").rglob("*.cs")) if (pkg_path / "Files").exists() else []
            autogen_cs = list((pkg_path / "Autogenerated" / "Src").rglob("*.cs")) if (pkg_path / "Autogenerated" / "Src").exists() else []
            js_files = list((pkg_path / "Files" / "src" / "js").rglob("*.js")) if (pkg_path / "Files" / "src" / "js").exists() else []

            pkg_stats.append({
                'name': name,
                'path': pkg_path,
                'authored_cs': len(authored_cs),
                'autogen_cs': len(autogen_cs),
                'js_files': len(js_files),
                'authored_paths': authored_cs,
                'autogen_paths': autogen_cs,
            })

        # Sort by authored C# count (most interesting first)
        pkg_stats.sort(key=lambda x: x['authored_cs'], reverse=True)

        if top_n:
            pkg_stats = pkg_stats[:top_n]
            log.info(f"Indexing top {top_n} packages by authored C# code")

        # Second pass: parse files
        for i, stats in enumerate(pkg_stats):
            name = stats['name']
            log.info(f"[{i+1}/{len(pkg_stats)}] {name}: "
                    f"{stats['authored_cs']} authored, {stats['autogen_cs']} autogen, "
                    f"{stats['js_files']} JS")

            pkg_index = PackageIndex(
                name=name,
                authored_cs=stats['authored_cs'],
                autogen_cs=stats['autogen_cs'],
                js_files=stats['js_files'],
                category=categorize_package(name),
            )

            # Read descriptor.json if it exists
            desc_path = stats['path'] / "Files" / "descriptor.json"
            if desc_path.exists():
                try:
                    pkg_index.descriptor = json.loads(desc_path.read_text(encoding='utf-8-sig'))
                    deps = pkg_index.descriptor.get('DependsOn', [])
                    pkg_index.dependencies = [d.get('PackageName', d.get('Name', '')) for d in deps if isinstance(d, dict)]
                except Exception:
                    pass

            # Parse authored C# files
            for cs_path in stats['authored_paths']:
                parsed = self.parser.parse_file(cs_path, name)
                pkg_index.files.append(parsed)

                # Collect entities, services, handlers
                if 'entity' in parsed.category:
                    for cls in parsed.classes:
                        pkg_index.entities.append(cls['name'])
                if 'web_service' in parsed.category or 'rest_service' in parsed.category:
                    for cls in parsed.classes:
                        pkg_index.services.append(cls['name'])
                if 'event' in parsed.category:
                    for cls in parsed.classes:
                        pkg_index.event_handlers.append(cls['name'])

            # Also parse autogenerated files (lighter — just class names for entity catalog)
            for cs_path in stats['autogen_paths']:
                try:
                    content = cs_path.read_text(encoding='utf-8-sig', errors='replace')
                    for match in self.parser.RE_CLASS.finditer(content):
                        class_name = match.group(1)
                        if class_name.endswith('_Terrasoft') or class_name.endswith('Schema'):
                            continue
                        pkg_index.entities.append(class_name)
                except Exception:
                    pass

            self.packages[name] = pkg_index

        # Write output
        self._write_index()
        self._write_pattern_report()
        self._write_entity_catalog()

        log.info("=" * 60)
        log.info(f"Index complete! Output: {self.output_dir}")
        log.info(f"Packages indexed: {len(self.packages)}")
        total_files = sum(p.authored_cs for p in self.packages.values())
        log.info(f"Authored C# files: {total_files}")
        log.info("=" * 60)

    def _write_index(self):
        """Write the full package index."""
        index = {}
        for name, pkg in self.packages.items():
            index[name] = {
                'name': name,
                'category': pkg.category,
                'authored_cs': pkg.authored_cs,
                'autogen_cs': pkg.autogen_cs,
                'js_files': pkg.js_files,
                'dependencies': pkg.dependencies,
                'entities': list(set(pkg.entities)),
                'services': list(set(pkg.services)),
                'event_handlers': list(set(pkg.event_handlers)),
                'file_categories': self._summarize_categories(pkg),
            }

        with open(self.output_dir / "package_index.json", 'w') as f:
            json.dump(index, f, indent=2)

        # Also write per-package detailed files
        pkg_detail_dir = self.output_dir / "packages"
        pkg_detail_dir.mkdir(exist_ok=True)

        for name, pkg in self.packages.items():
            detail = {
                'name': name,
                'category': pkg.category,
                'descriptor': pkg.descriptor,
                'dependencies': pkg.dependencies,
                'files': [
                    {
                        'filename': f.filename,
                        'namespace': f.namespace,
                        'classes': f.classes,
                        'methods': f.methods[:20],  # Cap
                        'properties': f.properties[:20],
                        'category': f.category,
                        'line_count': f.line_count,
                        'usings': f.usings,
                        'attributes': f.attributes,
                    }
                    for f in pkg.files if not f.is_autogenerated
                ],
                'entities': list(set(pkg.entities)),
                'services': list(set(pkg.services)),
                'event_handlers': list(set(pkg.event_handlers)),
            }
            with open(pkg_detail_dir / f"{name}.json", 'w') as f:
                json.dump(detail, f, indent=2)

    def _summarize_categories(self, pkg: PackageIndex) -> Dict[str, int]:
        """Count files per category in a package."""
        cats = defaultdict(int)
        for f in pkg.files:
            for cat in f.category.split(','):
                cats[cat.strip()] += 1
        return dict(cats)

    def _write_pattern_report(self):
        """Generate a markdown report of common patterns found."""
        md = f"""# Creatio 8.3 Source Code Pattern Report

**Generated:** {datetime.now().isoformat()}
**Packages indexed:** {len(self.packages)}

## Package Categories

| Category | Packages | Authored CS | Top Packages |
|----------|----------|-------------|--------------|
"""
        # Aggregate by category
        cat_stats = defaultdict(lambda: {'count': 0, 'cs': 0, 'names': []})
        for pkg in self.packages.values():
            cat = pkg.category
            cat_stats[cat]['count'] += 1
            cat_stats[cat]['cs'] += pkg.authored_cs
            cat_stats[cat]['names'].append(pkg.name)

        for cat, stats in sorted(cat_stats.items(), key=lambda x: -x[1]['cs']):
            top = ', '.join(stats['names'][:3])
            md += f"| {cat} | {stats['count']} | {stats['cs']} | {top} |\n"

        # Top packages by authored code
        md += "\n## Top 20 Packages by Authored C# Code\n\n"
        md += "| # | Package | Category | Authored CS | Entities | Services | Handlers |\n"
        md += "|---|---------|----------|-------------|----------|----------|----------|\n"

        sorted_pkgs = sorted(self.packages.values(), key=lambda p: p.authored_cs, reverse=True)
        for i, pkg in enumerate(sorted_pkgs[:20]):
            md += (f"| {i+1} | {pkg.name} | {pkg.category} | {pkg.authored_cs} | "
                  f"{len(set(pkg.entities))} | {len(set(pkg.services))} | "
                  f"{len(set(pkg.event_handlers))} |\n")

        # Common base classes
        md += "\n## Common Base Classes\n\n"
        base_counts = defaultdict(int)
        for pkg in self.packages.values():
            for f in pkg.files:
                for cls in f.classes:
                    for base in cls.get('bases', []):
                        base_counts[base.strip()] += 1

        md += "| Base Class | Usage Count |\n"
        md += "|-----------|-------------|\n"
        for base, count in sorted(base_counts.items(), key=lambda x: -x[1])[:30]:
            md += f"| `{base}` | {count} |\n"

        # Common namespaces
        md += "\n## Common Namespaces\n\n"
        ns_counts = defaultdict(int)
        for pkg in self.packages.values():
            for f in pkg.files:
                for using in f.usings:
                    ns_counts[using] += 1

        md += "| Namespace | Import Count |\n"
        md += "|-----------|-------------|\n"
        for ns, count in sorted(ns_counts.items(), key=lambda x: -x[1])[:30]:
            md += f"| `{ns}` | {count} |\n"

        (self.output_dir / "PATTERN_REPORT.md").write_text(md)

    def _write_entity_catalog(self):
        """Write a catalog of all entities found across packages."""
        entities = {}
        for pkg in self.packages.values():
            for entity in set(pkg.entities):
                if entity not in entities:
                    entities[entity] = {
                        'name': entity,
                        'packages': [],
                    }
                entities[entity]['packages'].append(pkg.name)

        # Sort by name
        sorted_entities = dict(sorted(entities.items()))

        with open(self.output_dir / "entity_catalog.json", 'w') as f:
            json.dump(sorted_entities, f, indent=2)

        # Markdown version
        md = f"# Creatio 8.3 Entity Catalog\n\n"
        md += f"**Total entities:** {len(sorted_entities)}\n\n"
        md += "| Entity | Package(s) |\n"
        md += "|--------|------------|\n"
        for name, info in sorted_entities.items():
            pkgs = ', '.join(info['packages'][:3])
            md += f"| {name} | {pkgs} |\n"

        (self.output_dir / "ENTITY_CATALOG.md").write_text(md)

    def show_status(self):
        """Show current index status."""
        index_file = self.output_dir / "package_index.json"
        if not index_file.exists():
            print("No index found. Run indexer first.")
            return

        index = json.loads(index_file.read_text())
        print(f"\nCreatio 8.3 Source Index Status")
        print(f"Packages indexed: {len(index)}")
        total_cs = sum(p['authored_cs'] for p in index.values())
        total_entities = sum(len(p['entities']) for p in index.values())
        print(f"Authored C# files: {total_cs}")
        print(f"Entities found: {total_entities}")
        print(f"Output: {self.output_dir}")


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description='Creatio 8.3 Source Code Indexer')
    parser.add_argument('--output-dir', type=str, default=str(DEFAULT_OUTPUT))
    parser.add_argument('--top', type=int, default=None,
                       help='Only index top N packages by code volume')
    parser.add_argument('--package', type=str, default=None,
                       help='Index a specific package')
    parser.add_argument('--patterns', action='store_true',
                       help='Only extract patterns from existing index')
    parser.add_argument('--status', action='store_true',
                       help='Show index status')
    parser.add_argument('--verbose', '-v', action='store_true')

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    indexer = SourceCodeIndexer(
        output_dir=Path(args.output_dir),
    )

    if args.status:
        indexer.show_status()
    else:
        indexer.index_all(top_n=args.top, package_filter=args.package)


if __name__ == '__main__':
    main()
