#!/bin/bash
# Deploy v51 Helper Script - FIX FOR PROD INFINITE LOADING
# Outputs the handler code for copy-paste to Creatio Designer

FILE="/home/magown/creatio-report-fix/client-module/BGApp_eykaguu_UsrPage_ebkv9e8_v51_StableDialog.js"

echo "=============================================="
echo "v51 DEPLOYMENT HELPER - INFINITE LOADING FIX"
echo "=============================================="
echo ""
echo "ROOT CAUSE: v50's modelConfigDiff added UsrCustomerEmbeddedDS data source"
echo "            that queries entire Account entity at page init, causing hang."
echo ""
echo "FIX: v51 has empty modelConfigDiff (no additional data sources)"
echo "     Uses Button + Dialog approach for Customer selection instead."
echo ""
echo "Target URL (PROD):"
echo "https://pampabay.creatio.com/0/ClientApp/#/ClientUnitSchemaDesigner/873d9fd9-98ac-4ece-9f53-9f77c5f4ddf2"
echo ""
echo "Steps:"
echo "1. Open the URL above in browser (login to PROD first)"
echo "2. Select all code in the editor (Ctrl+A)"
echo "3. Paste the code below (Ctrl+V)"
echo "4. Save (Ctrl+S)"
echo "5. Refresh the Reports page"
echo ""
echo "=============================================="
echo "CODE STARTS BELOW ($(wc -l < "$FILE") lines)"
echo "=============================================="
echo ""
cat "$FILE"
echo ""
echo "=============================================="
echo "CODE ENDS ABOVE"
echo "=============================================="
echo ""
echo "After deployment, check browser console for:"
echo "[v51] Page loaded - version indicator"
echo ""
echo "If page loads correctly (no infinite loading):"
echo "SUCCESS! The empty modelConfigDiff fixed the issue."
echo ""
echo "If page still hangs:"
echo "Check if parent schema BGlobalLookerStudio has issues."
