#!/bin/bash
# Deploy v52 Helper Script - FIX FOR CUSTOMER ID BUG
# Outputs the handler code for copy-paste to Creatio Designer

FILE="/home/magown/creatio-report-fix/client-module/BGApp_eykaguu_UsrPage_ebkv9e8_v52_CustomerFix.js"

echo "=============================================="
echo "v52 DEPLOYMENT HELPER - CUSTOMER ID FIX"
echo "=============================================="
echo ""
echo "BUG FIXED: Customer ID was showing as 'value' string instead of GUID"
echo ""
echo "ROOT CAUSE: Freedom UI attributes return {value: 'guid'} objects,"
echo "            not raw values. Code was passing object to backend."
echo ""
echo "FIX: Extract .value from attribute objects + GUID validation"
echo ""
echo "Target URL (PROD):"
echo "https://pampabay.creatio.com/0/ClientApp/#/ClientUnitSchemaDesigner/873d9fd9-98ac-4ece-9f53-9f77c5f4ddf2"
echo ""
echo "Steps:"
echo "1. Open the URL above in browser (login to PROD first)"
echo "2. Select all code in the editor (Ctrl+A)"
echo "3. Paste the code below (Ctrl+V)"
echo "4. Save (Ctrl+S)"
echo "5. Refresh the Reports page"
echo "6. Test: Select 'Items by Customer', click 'Select Customer', pick AAFES, Generate"
echo ""
echo "=============================================="
echo "CODE STARTS BELOW ($(wc -l < "$FILE") lines)"
echo "=============================================="
echo ""
cat "$FILE"
echo ""
echo "=============================================="
echo "CODE ENDS ABOVE"
echo "=============================================="
echo ""
echo "After deployment, check browser console for:"
echo "[v52] Customer attr raw: ... | extracted: <GUID>"
echo "[v52] Customer: AAFES | ID: <GUID>"
echo ""
echo "If it still shows 'value', the attribute structure is different than expected."
